export const LOAN_DETAILS_REQUEST = "LOAN_DETAILS_REQUEST";
export const LOAN_DETAILS_SUCCESS = "LOAN_DETAILS_SUCCESS";
export const LOAN_DETAILS_FAIL = "LOAN_DETAILS_FAIL";

export const LOAN_APPLICATION_REQUEST = "LOAN_APPLICATION_REQUEST";
export const LOAN_APPLICATION_SUCCESS = "LOAN_APPLICATION_SUCCESS";
export const LOAN_APPLICATION_FAIL = "LOAN_APPLICATION_FAIL";

export const PAYBACK_LOAN_REQUEST = "PAYBACK_LOAN_REQUEST";
export const PAYBACK_LOAN_SUCCESS = "PAYBACK_LOAN_SUCCESS";
export const PAYBACK_LOAN_FAIL = "PAYBACK_LOAN_FAIL";
export const PAYBACK_LOAN_RESET = "PAYBACK_LOAN_RESET";
